### ISSUE TITLE
[feature request] "subscribe to notifications" user preference available to all users

### ISSUE THREAD

**Issue by massey21** [usnistgov/NEMO#217] opened 2024-04-26 16:45 UTC
Can all users have access to this?
![image](https://github.com/usnistgov/NEMO/assets/98626874/3c503f99-bdd0-40ed-ba2e-7f771834b512)

Apologies if I've requested this before.  I couldn't find the old request.

I can't imagine a downside to allowing users to subscribe to tools, but if some institutions wanted to lock out the capability, you could add a checkbox/toggle in the admin customization page.

**Comment by massey21** [comment] 2024-04-26 16:49
Canceling. Duplicate of 188.

**Comment by rptmat57** [comment] 2024-04-26 16:50
closing as duplicate of #188

**Closed by rptmat57** 2024-04-26 16:50 UTC
