### ISSUE TITLE
"Usage Data History" Returns No Data

### ISSUE THREAD

**Issue by rmwhite85** [usnistgov/NEMO#164] opened 2023-09-26 19:07 UTC
When using NEMO version NEMO version 4.6.3, the "Usage Data History" for any specific tool only reports "No usage data was found between these dates."

Tool Control -> [TOOL] -> Usage Data History

**Comment by rptmat57** [comment] 2023-09-26 19:57
Hi Ryan, I believe this issue only happens for staff and is fixed by https://github.com/usnistgov/NEMO/commit/628bb29592e8f3958bb1aa4810114fe68f1ba76c
If you don't mind, could you please confirm by impersonating a regular user and making sure the system behaves as expected?

The fix will be in the next release (4.7.0)

**Comment by rptmat57** [comment] 2023-10-14 12:01
Closing as fixed in 4.7.0
Please reopen if the issue is still there

**Closed by rptmat57** 2023-10-14 12:01 UTC
