### ISSUE TITLE
Internal error when creating reservation from admin user

### ISSUE THREAD

**Issue by r-xyz** [usnistgov/NEMO#148] opened 2023-07-05 09:54 UTC
Hello,
I would like to report a minor bug we noticed on the latest version of NEMO (4.5.5). Not sure if it affected previous versions, but we did not experienced it in the past.
When creating a new reservation using the admin user, a 500 error pops up:
![image](https://github.com/usnistgov/NEMO/assets/100710244/f6d641f2-7cbd-4a9d-a886-d8c164f14c4d)

This is minor annoyance, since the reservation is still created (only calendar invitation is not sent).
Also the error does **not** appear in the following cases:
- regular users making reservation
- admin making reservations on behalf of other users (both impersonating or using the function in calendar)
- admin cancelling other user reservations

Checking the logs, we have the following error:
<details>
  <summary>Expand</summary>

```python

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]

During handling of the above exception ("'area"), another exception occurred:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/NEMO/views/calendar.py", line 362, in create_reservation
    return create_item_reservation(request, request.user, start, end, ReservationItemType(item_type), item_id)
  File "/usr/local/lib/python3.8/site-packages/NEMO/decorators.py", line 56, in decorator
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/NEMO/views/calendar.py", line 442, in create_item_reservation
    new_reservation.save_and_notify()
  File "/usr/local/lib/python3.8/site-packages/NEMO/models.py", line 1804, in save_and_notify
    send_user_created_reservation_notification(self)
  File "/usr/local/lib/python3.8/site-packages/NEMO/views/calendar.py", line 1170, in send_user_created_reservation_notification
    message = render_email_template(message, {'reservation': reservation})
  File "/usr/local/lib/python3.8/site-packages/NEMO/utilities.py", line 580, in render_email_template
    return Template(template).render(make_context(dictionary, request or EmptyHttpRequest()))
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 967, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 900, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/local/lib/python3.8/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 903, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "

Exception Type: TemplateSyntaxError at /create_reservation/
Exception Value: Could not parse the remainder: ''area' from ''area'
Request information:
USER: <REDACTED>

GET: No GET data

POST:
start = '1688653800'
end = '1688659200'
item_type = 'tool'
item_id = '3'
csrfmiddlewaretoken = <REDACTED>
reservation_questions = 'true'
df_Confirm = 'I confirm'

FILES: No FILES data
```
</details>

EDIT: the user affected is marked both as Staff and Admin, just in case this might help to reproduce it.

**Comment by rptmat57** [comment] 2023-07-05 19:47
Thank you for posting the logs.
Could you post your "reservation_created_user_email.html" template?
It looks like it could be coming from there

**Comment by r-xyz** [comment] 2023-07-06 13:20
Thanks Mathieu.
We have no template in place for `reservation_created_user_email.html`. Still an empty email with invitation shall be generate (as it is for cancellations).
The issue also appear when moving the reservation, as `TemplateSyntaxError at /move_reservation/`.
In this case, you end up with duplicated reservations, since from NEMO point of view it means cancelling the reservation and creating the previous one. This means the error in this case is probably generated before cancellation is performed.

**Comment by rptmat57** [comment] 2023-07-06 14:01
From the logs you posted, the error is coming from line 1170 in calendar.py -> [here](https://github.com/usnistgov/NEMO/blob/b355c62a37d1f6761f8f2e7e66ba284dbe1acf29/NEMO/views/calendar.py#L1170C73-L1170C73)
Which is when it tries to render the `reservation_created_user_email` template.
Would you mind double checking? try going to `<site_address>/media/reservation_created_user_email.html` and make sure you get a page not found exception.

Also, check that when impersonating, the user has the ics box checked in preferences.

I have not been able to reproduce it, could you try on the demo website? [https://nemo.nist.gov/demo](https://nemo.nist.gov/demo)

**Comment by r-xyz** [comment] 2023-07-06 14:27
Thanks again for the help.
The file `reservation_created_user_email.html` actually existed, but was not shown in `Customization` menu.
The content of the file was instead the one for the `Unauthorized Tool Access Email` template, which is why it generated the error.
Also you are right, I was not aware that the user I was trying to impersonate had ICS box disabled, so the error was not really tied to the admin user, but to the template.
The weird thing is the `Unauthorized Tool Access Email` template was uploaded using the Customization menu itself. 
So, I tried to delete it and re-upload it expecting to repeat the naming mismatch, but this time worked as expected and I was not able to reproduce it.
I would then close the issue, since I cannot reproduce anymore.

**Comment by rptmat57** [comment] 2023-07-06 14:43
Sounds good.
It could have been an old bug that uploaded the template to the wrong file or something like that, and that was fixed since.

**Closed by rptmat57** 2023-07-06 14:43 UTC
